<a href="https://colab.research.google.com/github/hitaxi-04/PDS/blob/main/practical_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.5.2


In [ ]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print("Type:", type(a))
print("Shape:", a1.shape)
print("Dimension:", a1.ndim)

[1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Dimension: 1


In [ ]:
a2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a2)
print("Shape:", a2.shape)
print("Dimension:", a2.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimension: 2


In [ ]:
a3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(a3)
print("Shape:", a3.shape)
print("Dimension:", a3.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Dimension: 3


In [ ]:
zeros = np.zeros((1, 2))
print(zeros)

[[0. 0.]]


In [ ]:
ones = np.ones((1, 2))
print(ones)

[[1. 1.]]


In [ ]:
numbers = np.arange(1, 7)
print(numbers)

[1 2 3 4 5 6]


In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a)
print("second row last element:",a[1, 2])
print("last element",a[-1, -1])
print("first row:",a[1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
second row last element: 6
last element 9
first row: [4 5 6]


In [ ]:
#slicing
print("3rd column:",a[:, 2])
print(a[:, 0:2])
print(a[0:2, 1:2])

3rd column: [3 6 9]
[[1 2]
 [4 5]
 [7 8]]
[[2]
 [5]]


In [ ]:
#reshape
a = np.arange(1, 13)
print(a)
r = a.reshape(3, 4)
print("reshape array:",r)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
reshape array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#brodcasting
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
r = a + 5
print(r)
#i-D array
v = np.array([1, 2, 3])
res= a + v
print(res)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [ ]:
a = np.array([
    [1, 2],
    [3, 4]
])
b = np.array([
    [5, 6],
    [7, 8]
])
print("sum:",a + b)
print("substraction:",b - a)
print("multiplication:",a * b)
print("division:",b/a)
print(a ** 2)

sum: [[ 6  8]
 [10 12]]
substraction: [[4 4]
 [4 4]]
multiplication: [[ 5 12]
 [21 32]]
division: [[5.         3.        ]
 [2.33333333 2.        ]]
[[ 1  4]
 [ 9 16]]


In [ ]:
#mathematical functions
a= np.array([
    [1, 4, 9],
    [16, 25, 36]
])
print(np.sqrt(a))
print(np.log(a))
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Maximum:", np.max(a))
print("Minimum:", np.min(a))

[[1. 2. 3.]
 [4. 5. 6.]]
[[0.         1.38629436 2.19722458]
 [2.77258872 3.21887582 3.58351894]]
Sum: 91
Mean: 15.166666666666666
Maximum: 36
Minimum: 1


In [ ]:
#sum of each columns and rows
print("sum of columns:",np.sum(a, axis=0))
print("sum of rows:",np.sum(a, axis=1))

sum of columns: [17 29 45]
sum of rows: [14 77]


In [ ]:
#matrix multiplication
a = np.array([
    [1, 2],
    [3, 4]
])
b = np.array([
    [5, 6],
    [7, 8]
])
result = a @ b #@=np.matmul()
print(result)

[[19 22]
 [43 50]]


In [ ]:
import numpy as np

# 1. Array creation
arr = np.arange(1, 13)

print("Original Array:")
print(arr)

# 2. Reshaping
arr = arr.reshape(3, 4)

print("\nReshaped Array:")
print(arr)

# 3. Indexing
print("\nElement at row 2, column 3:")
print(arr[1, 2])

# 4. Slicing
print("\nFirst two rows:")
print(arr[0:2])

print("\nFirst two columns:")
print(arr[:, 0:2])

# 5. Broadcasting
print("\nAfter adding 10:")
print(arr + 10)

# 6. Mathematical operations
print("\nArray multiplied by 2:")
print(arr * 2)

print("\nArray squared:")
print(arr ** 2)

# 7. Statistical operations
print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at row 2, column 3:
7

First two rows:
[[1 2 3 4]
 [5 6 7 8]]

First two columns:
[[ 1  2]
 [ 5  6]
 [ 9 10]]

After adding 10:
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]

Array multiplied by 2:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Array squared:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Sum: 78
Mean: 6.5
Maximum: 12
Minimum: 1
